version: '3.8'

services:
  ApprovalServerDatabase:
      container_name: ApprovalServerDatabase
      image: mysql
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: ApprovalServerDatabase
        MYSQL_USER: user
        MYSQL_PASSWORD: Toot
      volumes:
        - ./mysql:/var/lib/mysql
        - ./init:/docker-entrypoint-initdb.d

volumes:
  mysql:

